# Generated by Django 4.2.3 on 2024-10-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='target_date',
            new_name='date',
        ),
    ]
