# Generated by Django 4.2.3 on 2024-10-12 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_target_date_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[(datetime.timedelta(days=1), 'DAILY'), (datetime.timedelta(days=7), 'WEEKLY'), (datetime.timedelta(days=30), 'MONTHLY')], max_length=20, null=True),
        ),
    ]
