# Generated by Django 4.2.3 on 2024-10-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_end_date_alter_task_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
    ]
