# Generated by Django 4.2.3 on 2024-10-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_groups_rename_end_date_task_due_date_task_completed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groups',
            new_name='group',
        ),
    ]
